# Generated by Django 3.2.9 on 2021-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(through='articles.ScopePosition', to='articles.Scope'),
        ),
    ]
